services:
  - type: web
    name: livzo-app
    env: node
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AUTH_JWT_SECRET
        generateValue: true
      - key: AUTH_REFRESH_SECRET
        generateValue: true
